const INCREMENTO = 'INCREMENTO';
const DECREMENTO = 'DECREMENTO';
const INCREMENTOIMPAR = "INCREMENTO IMPAR"
const INCREMENTOASYNC = "INCREMENTO ASYNCS"

module.exports = {
  INCREMENTO,
  DECREMENTO,
  INCREMENTOIMPAR,
  INCREMENTOASYNC
}